const conversionData = {
  he: {
    cups: [
      { item: "כוס קמח  (רגיל או תופח)", amount: "140 גרם" },
      { item: "כוס קמח מלא", amount: "125 גרם" },
      { item: "כוס סוכר", amount: "200 גרם" },
      { item: "כוס סוכר חום דחוס", amount: "225 גרם" },
      { item: "כוס חמאה", amount: "230 גרם" },
      { item: "כוס אבקת סוכר", amount: "120 גרם" },
      { item: "כוס אגוזים טחונים", amount: "110 גרם" },
      { item: "כוס אגוזים קצוצים", amount: "100 גרם" },
      { item: "כוס אורז ארוך", amount: "200 גרם" },
      { item: "כוס אורז קצר", amount: "210 גרם" },
      { item: "כוס דבש / סירופ מייפל", amount: "320 גרם" },
      { item: "כוס ריבה", amount: "320 גרם" },
      { item: "כוס חמאת בוטנים", amount: "280 גרם" },
      { item: "כוס מלח", amount: "290 גרם" },
      { item: "כוס פירות יבשים קצוצים", amount: "150 גרם" },
      { item: "כוס פירורי לחם", amount: "125 גרם" },
      { item: "כוס פירורי עוגיות", amount: "110 גרם" },
      { item: "כוס צימוקים", amount: "140 גרם" },
      { item: "כוס קוקוס טחון", amount: "70 גרם" },
      { item: "כוס קורנפלור", amount: "140 גרם" },
      { item: "כוס קקאו", amount: "140 גרם" },
      { item: "כוס שוקולד צ'יפס", amount: "200 גרם" },
      { item: "כוס שיבולת שועל", amount: "100 גרם" },
      { item: "כוס שמן", amount: "200 גרם" },
    ],
    spoons: [
      { item: "כף קמח", amount: "10 גרם" },
      { item: "כף סוכר", amount: "12 גרם" },
      { item: "כף מלח", amount: "18 גרם" },
      { item: "כף שמרים יבשים", amount: "10 גרם" },
      { item: "כף חמאה", amount: "15 גרם" },
      { item: "כף אבקת אפייה / אבקת סוכר", amount: "10 גרם" },
      { item: "כף אגוזים/שקדים קצוצים", amount: "6 גרם" },
      { item: "כף אבקת ג'לטין", amount: "10 גרם" },
      { item: "כף דבש", amount: "22 גרם" },
      { item: "כף סודה לשתייה", amount: "10 גרם" },
      { item: "כף קורנפלור", amount: "10 גרם" },
    ],
    teaspoons: [
      { item: "כפית אבקת אפייה / אבקת סוכר", amount: "3 גרם" },
      { item: "כפית מלח", amount: "6 גרם" },
      { item: "כפית סודה לשתייה", amount: "3 גרם" },
      { item: "כפית סוכר", amount: "4 גרם" },
      { item: "כפית גדושה סוכר חום", amount: "5 גרם" },
      { item: "כפית קמח", amount: "3 גרם" },
    ],
    temperature: [
      { celsius: "105", fahrenheit: "225", heat: "חום נמוך מאוד" },
      { celsius: "120", fahrenheit: "250", heat: "חום נמוך מאוד" },
      { celsius: "135", fahrenheit: "275", heat: "חום נמוך מאוד" },
      { celsius: "150", fahrenheit: "300", heat: "חום נמוך" },
      { celsius: "160", fahrenheit: "325", heat: "חום בינוני-נמוך" },
      { celsius: "175", fahrenheit: "350", heat: "חום בינוני" },
      { celsius: "180", fahrenheit: "356", heat: "חום בינוני" },
      { celsius: "190", fahrenheit: "375", heat: "חום בינוני-גבוה" },
      { celsius: "205", fahrenheit: "400", heat: "חום גבוה" },
      { celsius: "220", fahrenheit: "425", heat: "חום גבוה" },
      { celsius: "230", fahrenheit: "450", heat: "חום גבוה מאוד" },
      { celsius: "245", fahrenheit: "475", heat: "חום גבוה מאוד" },
    ],
    pans: [
      { from: "מקוטר 22 ל-24", change: "20%+" },
      { from: "מקוטר 22 ל-26", change: "40%+" },
      { from: "מקוטר 22 ל-28", change: "60%+" },
      { from: "מקוטר 26 ל-24", change: "15%-" },
      { from: "מקוטר 26 ל-22", change: "30%-" },
      { from: "מקוטר 28 ל-22", change: "40%-" },
    ],
    universal: [
      { item: "1 כוס", amount: '240 מ"ל' },
      { item: "1 כף", amount: '15 מ"ל' },
      { item: "1 כפית", amount: '5 מ"ל' },
      { item: "1 כף", amount: "3 כפיות" },
      { item: "1 כוס", amount: "16 כפות" },
    ],
    eggs: [
      { item: "ביצה בגודל M", amount: "53-62 גרם" },
      { item: "ביצה בגודל L", amount: "63-72 גרם" },
      { item: "ביצה בגודל XL", amount: "73 גרם" },
      { item: "חלבון ביצה בגודל M", amount: "25-30 גרם" },
      { item: "חלבון ביצה בגודל L", amount: "30-35 גרם" },
      { item: "חלבון ביצה בגודל XL", amount: "40-45 גרם" },
    ],
    general: [
      { item: "1 כוס קמח תופח", amount: "1 כוס קמח רגיל + כפית אבקת אפייה" },
      { item: "1 קילו קמח תופח", amount: "1 קילו קמח רגיל + 2 שקיות אבקת אפייה (10 גרם כל אחת)" },
      { item: "שקית שמרים טריים (50 גרם)", amount: "קצת פחות מ-2 כפות שמרים יבשים (17 גרם)" },
      { item: "100 גרם חמאה", amount: "85 גרם שמן" },
    ],
    faq: [
      { question: "כמה כוסות הן חצי קילו קמח (500 גרם)?", answer: "3 כוסות וחצי + כף קמח" },
      { question: "כמה כוסות הן קילו אורז?", answer: "5 כוסות" },
      { question: "כמה כוסות הן 200 גרם קמח?", answer: "כוס וחצי קמח מינוס כף" },
    ],
  },
  en: {
    cups: [
      { item: "Cup of whole flour (regular or self-rising)", amount: "140g" },
      { item: "Cup of whole flour", amount: "125g" },
      { item: "Cup of sugar", amount: "200g" },
      { item: "Cup of packed brown sugar", amount: "225g" },
      { item: "Cup of butter", amount: "230g" },
      { item: "Cup of powdered sugar", amount: "120g" },
      { item: "Cup of ground nuts", amount: "110g" },
      { item: "Cup of chopped nuts", amount: "100g" },
      { item: "Cup of long grain rice", amount: "200g" },
      { item: "Cup of short grain rice", amount: "210g" },
      { item: "Cup of honey / maple syrup", amount: "320g" },
      { item: "Cup of jam", amount: "320g" },
      { item: "Cup of peanut butter", amount: "280g" },
      { item: "Cup of salt", amount: "290g" },
      { item: "Cup of chopped dried fruits", amount: "150g" },
      { item: "Cup of bread crumbs", amount: "125g" },
      { item: "Cup of cookie crumbs", amount: "110g" },
      { item: "Cup of raisins", amount: "140g" },
      { item: "Cup of ground coconut", amount: "70g" },
      { item: "Cup of cornstarch", amount: "140g" },
      { item: "Cup of cocoa", amount: "140g" },
      { item: "Cup of chocolate chips", amount: "200g" },
      { item: "Cup of oats", amount: "100g" },
      { item: "Cup of oil", amount: "200g" },
    ],
    spoons: [
      { item: "Tbsp flour", amount: "10g" },
      { item: "Tbsp sugar", amount: "12g" },
      { item: "Tbsp salt", amount: "18g" },
      { item: "Tbsp dry yeast", amount: "10g" },
      { item: "Tbsp butter", amount: "15g" },
      { item: "Tbsp baking powder / powdered sugar", amount: "10g" },
      { item: "Tbsp chopped nuts/almonds", amount: "6g" },
      { item: "Tbsp gelatin powder", amount: "10g" },
      { item: "Tbsp honey", amount: "22g" },
      { item: "Tbsp baking soda", amount: "10g" },
      { item: "Tbsp cornstarch", amount: "10g" },
    ],
    teaspoons: [
      { item: "Tsp baking powder / powdered sugar", amount: "3g" },
      { item: "Tsp salt", amount: "6g" },
      { item: "Tsp baking soda", amount: "3g" },
      { item: "Tsp sugar", amount: "4g" },
      { item: "Heaped tsp brown sugar", amount: "5g" },
      { item: "Tsp flour", amount: "3g" },
    ],
    temperature: [
      { celsius: "105", fahrenheit: "225", heat: "Very low heat" },
      { celsius: "120", fahrenheit: "250", heat: "Very low heat" },
      { celsius: "135", fahrenheit: "275", heat: "Very low heat" },
      { celsius: "150", fahrenheit: "300", heat: "Low heat" },
      { celsius: "160", fahrenheit: "325", heat: "Medium-low heat" },
      { celsius: "175", fahrenheit: "350", heat: "Medium heat" },
      { celsius: "180", fahrenheit: "356", heat: "Medium heat" },
      { celsius: "190", fahrenheit: "375", heat: "Medium-high heat" },
      { celsius: "205", fahrenheit: "400", heat: "High heat" },
      { celsius: "220", fahrenheit: "425", heat: "High heat" },
      { celsius: "230", fahrenheit: "450", heat: "Very high heat" },
      { celsius: "245", fahrenheit: "475", heat: "Very high heat" },
    ],
    pans: [
      { from: "22cm to 24cm", change: "20%+" },
      { from: "22cm to 26cm", change: "40%+" },
      { from: "22cm to 28cm", change: "60%+" },
      { from: "26cm to 24cm", change: "15%-" },
      { from: "26cm to 22cm", change: "30%-" },
      { from: "28cm to 22cm", change: "40%-" },
    ],
    universal: [
      { item: "1 cup", amount: "240 ml" },
      { item: "1 tablespoon", amount: "15 ml" },
      { item: "1 teaspoon", amount: "5 ml" },
      { item: "1 tablespoon", amount: "3 teaspoons" },
      { item: "1 cup", amount: "16 tablespoons" },
    ],
    eggs: [
      { item: "Egg size M", amount: "53-62g" },
      { item: "Egg size L", amount: "63-72g" },
      { item: "Egg size XL", amount: "73g" },
      { item: "Egg white size M", amount: "25-30g" },
      { item: "Egg white size L", amount: "30-35g" },
      { item: "Egg white size XL", amount: "40-45g" },
    ],
    general: [
      { item: "1 cup self-rising flour", amount: "1 cup regular flour + 1 tsp baking powder" },
      { item: "1 kg self-rising flour", amount: "1 kg regular flour + 2 packets baking powder (10g each)" },
      { item: "Fresh yeast packet (50g)", amount: "Just under 2 tbsp dry yeast (17g)" },
      { item: "100g butter", amount: "85g oil" },
    ],
    faq: [
      { question: "How many cups is half a kilo of flour (500g)?", answer: "3.5 cups + 1 tbsp flour" },
      { question: "How many cups is a kilo of rice?", answer: "5 cups" },
      { question: "How many cups is 200g of flour?", answer: "1.5 cups minus 1 tbsp" },
    ],
  },
  ru: {
    cups: [
      { item: "Стакан муки (обычной или самоподнимающейся)", amount: "140 г" },
      { item: "Стакан цельной муки", amount: "125 г" },
      { item: "Стакан сахара", amount: "200 г" },
      { item: "Стакан коричневого сахара (утрамб.)", amount: "225 г" },
      { item: "Стакан масла", amount: "230 г" },
      { item: "Стакан сахарной пудры", amount: "120 г" },
      { item: "Стакан молотых орехов", amount: "110 г" },
      { item: "Стакан рубленых орехов", amount: "100 г" },
      { item: "Стакан длиннозёрного риса", amount: "200 г" },
      { item: "Стакан круглозёрного риса", amount: "210 г" },
      { item: "Стакан мёда / кленового сиропа", amount: "320 г" },
      { item: "Стакан варенья", amount: "320 г" },
      { item: "Стакан арахисовой пасты", amount: "280 г" },
      { item: "Стакан соли", amount: "290 г" },
      { item: "Стакан нарезанных сухофруктов", amount: "150 г" },
      { item: "Стакан панировочных сухарей", amount: "125 г" },
      { item: "Стакан крошки печенья", amount: "110 г" },
      { item: "Стакан изюма", amount: "140 г" },
      { item: "Стакан молотого кокоса", amount: "70 г" },
      { item: "Стакан кукурузного крахмала", amount: "140 г" },
      { item: "Стакан какао", amount: "140 г" },
      { item: "Стакан шоколадных капель", amount: "200 г" },
      { item: "Стакан овсяных хлопьев", amount: "100 г" },
      { item: "Стакан масла", amount: "200 г" },
    ],
    spoons: [
      { item: "Ст. л. муки", amount: "10 г" },
      { item: "Ст. л. сахара", amount: "12 г" },
      { item: "Ст. л. соли", amount: "18 г" },
      { item: "Ст. л. сухих дрожжей", amount: "10 г" },
      { item: "Ст. л. масла", amount: "15 г" },
      { item: "Ст. л. разрыхлителя / сах. пудры", amount: "10 г" },
      { item: "Ст. л. рубленых орехов/миндаля", amount: "6 г" },
      { item: "Ст. л. желатина", amount: "10 г" },
      { item: "Ст. л. мёда", amount: "22 г" },
      { item: "Ст. л. соды", amount: "10 г" },
      { item: "Ст. л. крахмала", amount: "10 г" },
    ],
    teaspoons: [
      { item: "Ч. л. разрыхлителя / сах. пудры", amount: "3 г" },
      { item: "Ч. л. соли", amount: "6 г" },
      { item: "Ч. л. соды", amount: "3 г" },
      { item: "Ч. л. сахара", amount: "4 г" },
      { item: "Ч. л. с горкой коричневого сахара", amount: "5 г" },
      { item: "Ч. л. муки", amount: "3 г" },
    ],
    temperature: [
      { celsius: "105", fahrenheit: "225", heat: "Очень низкий" },
      { celsius: "120", fahrenheit: "250", heat: "Очень низкий" },
      { celsius: "135", fahrenheit: "275", heat: "Очень низкий" },
      { celsius: "150", fahrenheit: "300", heat: "Низкий" },
      { celsius: "160", fahrenheit: "325", heat: "Средне-низкий" },
      { celsius: "175", fahrenheit: "350", heat: "Средний" },
      { celsius: "180", fahrenheit: "356", heat: "Средний" },
      { celsius: "190", fahrenheit: "375", heat: "Средне-высокий" },
      { celsius: "205", fahrenheit: "400", heat: "Высокий" },
      { celsius: "220", fahrenheit: "425", heat: "Высокий" },
      { celsius: "230", fahrenheit: "450", heat: "Очень высокий" },
      { celsius: "245", fahrenheit: "475", heat: "Очень высокий" },
    ],
    pans: [
      { from: "С 22 на 24 см", change: "20%+" },
      { from: "С 22 на 26 см", change: "40%+" },
      { from: "С 22 на 28 см", change: "60%+" },
      { from: "С 26 на 24 см", change: "15%-" },
      { from: "С 26 на 22 см", change: "30%-" },
      { from: "С 28 на 22 см", change: "40%-" },
    ],
    universal: [
      { item: "1 стакан", amount: "240 мл" },
      { item: "1 ст. ложка", amount: "15 мл" },
      { item: "1 ч. ложка", amount: "5 мл" },
      { item: "1 ст. ложка", amount: "3 ч. ложки" },
      { item: "1 стакан", amount: "16 ст. ложек" },
    ],
    eggs: [
      { item: "Яйцо размера M", amount: "53-62 г" },
      { item: "Яйцо размера L", amount: "63-72 г" },
      { item: "Яйцо размера XL", amount: "73 г" },
      { item: "Белок яйца M", amount: "25-30 г" },
      { item: "Белок яйца L", amount: "30-35 г" },
      { item: "Белок яйца XL", amount: "40-45 г" },
    ],
    general: [
      { item: "1 стакан самоподн. муки", amount: "1 стакан обычной муки + 1 ч. л. разрыхлителя" },
      { item: "1 кг самоподн. муки", amount: "1 кг обычной муки + 2 пакетика разрыхлителя (по 10 г)" },
      { item: "Пачка свежих дрожжей (50 г)", amount: "Чуть меньше 2 ст. л. сухих дрожжей (17 г)" },
      { item: "100 г масла", amount: "85 г растительного масла" },
    ],
    faq: [
      { question: "Сколько стаканов в 500 г муки?", answer: "3,5 стакана + 1 ст. л. муки" },
      { question: "Сколько стаканов в 1 кг риса?", answer: "5 стаканов" },
      { question: "Сколько стаканов в 200 г муки?", answer: "1,5 стакана минус 1 ст. л." },
    ],
  },
  de: {
    cups: [
      { item: "Tasse Mehl (normal oder selbstaufgehend)", amount: "140g" },
      { item: "Tasse Vollkornmehl", amount: "125g" },
      { item: "Tasse Zucker", amount: "200g" },
      { item: "Tasse brauner Zucker (gepresst)", amount: "225g" },
      { item: "Tasse Butter", amount: "230g" },
      { item: "Tasse Puderzucker", amount: "120g" },
      { item: "Tasse gemahlene Nüsse", amount: "110g" },
      { item: "Tasse gehackte Nüsse", amount: "100g" },
      { item: "Tasse Langkornreis", amount: "200g" },
      { item: "Tasse Rundkornreis", amount: "210g" },
      { item: "Tasse Honig / Ahornsirup", amount: "320g" },
      { item: "Tasse Marmelade", amount: "320g" },
      { item: "Tasse Erdnussbutter", amount: "280g" },
      { item: "Tasse Salz", amount: "290g" },
      { item: "Tasse gehackte Trockenfrüchte", amount: "150g" },
      { item: "Tasse Semmelbrösel", amount: "125g" },
      { item: "Tasse Kekskrümel", amount: "110g" },
      { item: "Tasse Rosinen", amount: "140g" },
      { item: "Tasse gemahlene Kokosnuss", amount: "70g" },
      { item: "Tasse Speisestärke", amount: "140g" },
      { item: "Tasse Kakao", amount: "140g" },
      { item: "Tasse Schokoladenstückchen", amount: "200g" },
      { item: "Tasse Haferflocken", amount: "100g" },
      { item: "Tasse Öl", amount: "200g" },
    ],
    spoons: [
      { item: "EL Mehl", amount: "10g" },
      { item: "EL Zucker", amount: "12g" },
      { item: "EL Salz", amount: "18g" },
      { item: "EL Trockenhefe", amount: "10g" },
      { item: "EL Butter", amount: "15g" },
      { item: "EL Backpulver / Puderzucker", amount: "10g" },
      { item: "EL gehackte Nüsse/Mandeln", amount: "6g" },
      { item: "EL Gelatinepulver", amount: "10g" },
      { item: "EL Honig", amount: "22g" },
      { item: "EL Natron", amount: "10g" },
      { item: "EL Speisestärke", amount: "10g" },
    ],
    teaspoons: [
      { item: "TL Backpulver / Puderzucker", amount: "3g" },
      { item: "TL Salz", amount: "6g" },
      { item: "TL Natron", amount: "3g" },
      { item: "TL Zucker", amount: "4g" },
      { item: "Gehäufter TL brauner Zucker", amount: "5g" },
      { item: "TL Mehl", amount: "3g" },
    ],
    temperature: [
      { celsius: "105", fahrenheit: "225", heat: "Sehr niedrig" },
      { celsius: "120", fahrenheit: "250", heat: "Sehr niedrig" },
      { celsius: "135", fahrenheit: "275", heat: "Sehr niedrig" },
      { celsius: "150", fahrenheit: "300", heat: "Niedrig" },
      { celsius: "160", fahrenheit: "325", heat: "Mittel-niedrig" },
      { celsius: "175", fahrenheit: "350", heat: "Mittel" },
      { celsius: "180", fahrenheit: "356", heat: "Mittel" },
      { celsius: "190", fahrenheit: "375", heat: "Mittel-hoch" },
      { celsius: "205", fahrenheit: "400", heat: "Hoch" },
      { celsius: "220", fahrenheit: "425", heat: "Hoch" },
      { celsius: "230", fahrenheit: "450", heat: "Sehr hoch" },
      { celsius: "245", fahrenheit: "475", heat: "Sehr hoch" },
    ],
    pans: [
      { from: "22cm auf 24cm", change: "20%+" },
      { from: "22cm auf 26cm", change: "40%+" },
      { from: "22cm auf 28cm", change: "60%+" },
      { from: "26cm auf 24cm", change: "15%-" },
      { from: "26cm auf 22cm", change: "30%-" },
      { from: "28cm auf 22cm", change: "40%-" },
    ],
    universal: [
      { item: "1 Tasse", amount: "240 ml" },
      { item: "1 Esslöffel", amount: "15 ml" },
      { item: "1 Teelöffel", amount: "5 ml" },
      { item: "1 Esslöffel", amount: "3 Teelöffel" },
      { item: "1 Tasse", amount: "16 Esslöffel" },
    ],
    eggs: [
      { item: "Ei Größe M", amount: "53-62g" },
      { item: "Ei Größe L", amount: "63-72g" },
      { item: "Ei Größe XL", amount: "73g" },
      { item: "Eiweiß Größe M", amount: "25-30g" },
      { item: "Eiweiß Größe L", amount: "30-35g" },
      { item: "Eiweiß Größe XL", amount: "40-45g" },
    ],
    general: [
      { item: "1 Tasse selbstaufgehendes Mehl", amount: "1 Tasse normales Mehl + 1 TL Backpulver" },
      { item: "1 kg selbstaufgehendes Mehl", amount: "1 kg normales Mehl + 2 Päckchen Backpulver (je 10g)" },
      { item: "Frischhefe-Packung (50g)", amount: "Knapp 2 EL Trockenhefe (17g)" },
      { item: "100g Butter", amount: "85g Öl" },
    ],
    faq: [
      { question: "Wie viele Tassen sind 500g Mehl?", answer: "3,5 Tassen + 1 EL Mehl" },
      { question: "Wie viele Tassen sind 1 kg Reis?", answer: "5 Tassen" },
      { question: "Wie viele Tassen sind 200g Mehl?", answer: "1,5 Tassen minus 1 EL" },
    ],
  },
};

conversionData.mixed = conversionData.he;

export default conversionData;
