import {
  Utensils,
  CakeSlice,
  IceCreamCone,
  Coffee,
  Pizza,
  Soup,
  Croissant,
  Fish,
  Sandwich,
  Hamburger,
  EggFried,
  Beef,
  Drumstick,
  Ham,
  Slice,
  CookingPot,
  Cookie,
  Dessert,
  Salad,
  Leaf,
  LeafyGreen,
  Flame,
  Clock,
  Star,
  Heart,
  Snowflake,
  Sun,
  Wheat,
  Cherry,
  CupSoda,
  Milk,
  UtensilsCrossed,
} from "lucide-react";
import { TbGrill } from "react-icons/tb";

export const CATEGORY_ICONS = [
  { id: "restaurant", icon: Utensils },
  { id: "flatware", icon: UtensilsCrossed },
  { id: "bakery", icon: Croissant },
  { id: "cake", icon: CakeSlice },
  { id: "cupcake", icon: Dessert },
  { id: "cookie", icon: Cookie },
  { id: "icecream", icon: IceCreamCone },
  { id: "salad", icon: Salad },
  { id: "soup", icon: Soup },
  { id: "pizza", icon: Pizza },
  { id: "ramen", icon: Soup },
  { id: "noodles", icon: Soup },
  { id: "sushi", icon: Fish },
  { id: "setMeal", icon: Fish },
  { id: "kebab", icon: Ham },
  { id: "lunch", icon: Hamburger },
  { id: "brunch", icon: Sandwich },
  { id: "egg", icon: EggFried },
  { id: "grill", icon: TbGrill },
  { id: "meat", icon: Beef },
  { id: "bread", icon: Croissant },
  { id: "chicken", icon: Drumstick },
  { id: "beef", icon: Beef },
  { id: "meatCleaver", icon: Slice },
  { id: "cookingPot", icon: CookingPot },
  { id: "blender", icon: CupSoda },
  { id: "bowlFood", icon: Soup },
  { id: "fruitBowl", icon: Cherry },
  { id: "avocado", icon: LeafyGreen },
  { id: "leaf", icon: Leaf },
  { id: "wheat", icon: Wheat },
  { id: "chopsticks", icon: Utensils },
  { id: "cafe", icon: Coffee },
  { id: "coffee", icon: Coffee },
  { id: "tea", icon: Milk },
  { id: "fire", icon: Flame },
  { id: "flame", icon: Flame },
  { id: "clock", icon: Clock },
  { id: "heart", icon: Heart },
  { id: "star", icon: Star },
  { id: "snowflake", icon: Snowflake },
  { id: "sun", icon: Sun },
  { id: "dining", icon: UtensilsCrossed },
];

export const DEFAULT_ICON_ID = "restaurant";

export function getCategoryIcon(iconId) {
  const found = CATEGORY_ICONS.find((i) => i.id === iconId);
  return found ? found.icon : CATEGORY_ICONS[0].icon;
}
